import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAJVEER
 */
public class book extends javax.swing.JFrame {

    /**
     * Creates new form book
     */
    public book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        s1 = new javax.swing.JComboBox<>();
        detail = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phon = new javax.swing.JFormattedTextField();
        user = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(432, 460));
        setPreferredSize(new java.awt.Dimension(605, 390));
        setResizable(false);
        setSize(new java.awt.Dimension(605, 390));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Proceed To Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 390, 170, 30);

        t1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(10, 102, 136, 30);

        t2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(t2);
        t2.setBounds(10, 179, 136, 30);

        t3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(t3);
        t3.setBounds(10, 249, 136, 30);

        t4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(t4);
        t4.setBounds(10, 315, 136, 30);

        t5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(t5);
        t5.setBounds(10, 390, 136, 30);

        p1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        p1.setForeground(new java.awt.Color(0, 0, 153));
        p1.setText("Passenger 1");
        getContentPane().add(p1);
        p1.setBounds(10, 64, 110, 32);

        p2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        p2.setForeground(new java.awt.Color(0, 0, 153));
        p2.setText("Passenger 2");
        getContentPane().add(p2);
        p2.setBounds(10, 141, 120, 32);

        p3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        p3.setForeground(new java.awt.Color(0, 0, 153));
        p3.setText("Passenger 3");
        getContentPane().add(p3);
        p3.setBounds(10, 213, 120, 30);

        p4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        p4.setForeground(new java.awt.Color(0, 0, 153));
        p4.setText("Passenger 4");
        getContentPane().add(p4);
        p4.setBounds(10, 283, 110, 26);

        p5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        p5.setForeground(new java.awt.Color(0, 0, 153));
        p5.setText("Passenger 5");
        getContentPane().add(p5);
        p5.setBounds(10, 350, 110, 31);

        s1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        s1.setForeground(new java.awt.Color(0, 0, 153));
        s1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        s1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                s1ItemStateChanged(evt);
            }
        });
        getContentPane().add(s1);
        s1.setBounds(460, 170, 120, 30);

        detail.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        detail.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(detail);
        detail.setBounds(310, 30, 254, 35);

        price.setEditable(false);
        price.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(price);
        price.setBounds(460, 240, 120, 30);

        total.setEditable(false);
        total.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(total);
        total.setBounds(460, 310, 120, 30);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Price Per Ticket");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 210, 140, 30);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Rs");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 240, 28, 30);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Grand Total");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 280, 130, 30);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Rs");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 310, 20, 30);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Phone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 360, 52, 28);

        try {
            phon.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(phon);
        phon.setBounds(460, 390, 120, 30);

        user.setEditable(false);
        user.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(user);
        user.setBounds(460, 100, 120, 30);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("User ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 80, 80, 24);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IndiGo_Logo.jpg"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(570, 432));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 10, 60, 59);

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(203, 313, 120, 30);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Passenger No.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(460, 140, 130, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 600, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void close()
{
    WindowEvent winClose=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClose);
}
double amount, amount1;
private void passenger()
{
 book.p1.setEnabled(false);
 book.t1.setEnabled(false);
 book.p2.setEnabled(false);
 book.t2.setEnabled(false);
 book.p3.setEnabled(false);
 book.t3.setEnabled(false);
 book.p4.setEnabled(false);
 book.t4.setEnabled(false);
 book.p5.setEnabled(false);
 book.t5.setEnabled(false);
}
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
Font f=user.getFont();
        phon.setFont(f);
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String name1="";
String name2="";
String name3="";
String name4="";
String name5="";
String phone="";
String phone1=phon.getText();
long phone2=Long.parseLong(phon.getText());
String nam1=t1.getText();
String nam2=t2.getText();
String nam3=t3.getText();
String nam4=t4.getText();
String nam5=t5.getText();
String empty="";
int l=phone1.length();
int n=s1.getSelectedIndex()+1;
switch(n)
{
 case 1:
 if(!nam1.equals(empty) && phone2>=1000000000)
 {
  close();
  credit g=new credit();
  g.setVisible(true);
  credit.passno.setText(""+n);
  credit.total1.setText(""+total.getText());
 }        
 else
 {
  if(nam1.equals(empty))
  {
   name1="\n"+"Passenger 1 Name";
  }     
  if(phone2<1000000000)
  {
   phone="\n"+"Phone Number";
  }  
  String j="Please Select"+name1+phone+".";
  JOptionPane.showMessageDialog(this, j);
 }
 break;
 case 2:
 if(!nam1.equals(empty) && !nam2.equals(empty) && phone2>=1000000000)
 {
  close();
  credit g=new credit();
  g.setVisible(true);
  credit.passno.setText(""+n);
  credit.total1.setText(""+total.getText());
 }
 else
 {
  if(nam1.equals(empty))
  {
   name1="\n"+"Passenger 1 Name";
  }     
  if(nam2.equals(empty))
  {
   name2="\n"+"Passenger 2 Name";
  }
  if(phone2<1000000000)
  {
   phone="\n"+"Phone Number";
  }    
  String j="Please Select"+name1+name2+phone+".";
  JOptionPane.showMessageDialog(this, j);
 }
 break;
 case 3:
 if(!nam1.equals(empty) && !nam2.equals(empty) && !nam3.equals(empty) && phone2>=1000000000)
 {
  close();
  credit g=new credit();
  g.setVisible(true);
  credit.passno.setText(""+n);
  credit.total1.setText(""+total.getText());
 }
 else
 {
  if(nam1.equals(empty))
  {
   name1="\n"+"Passenger 1 Name";
  }     
  if(nam2.equals(empty))
  {
   name2="\n"+"Passenger 2 Name";
  }
  if(nam3.equals(empty))
  {
   name3="\n"+"Passenger 3 Name";
  }
  if(phone2<1000000000)
  {
   phone="\n"+"Phone Number";
  }    
  String j="Please Select"+name1+name2+name3+phone+".";
  JOptionPane.showMessageDialog(this, j);
 }
 break;
 case 4:
 if(!nam1.equals(empty) && !nam2.equals(empty) && !nam3.equals(empty) && !nam4.equals(empty) 
    && phone2>=1000000000)
 {
  close();
  credit g=new credit();
  g.setVisible(true);
  credit.passno.setText(""+n);
  credit.total1.setText(""+total.getText());
 }
 else
 {
  if(nam1.equals(empty))
  {
   name1="\n"+"Passenger 1 name";
  }     
  if(nam2.equals(empty))
  {
   name2="\n"+"Passenger 2 Name";
  }
  if(nam3.equals(empty))
  {
   name3="\n"+"Passenger 3 Name";
  }
  if(nam4.equals(empty))
  {
   name4="\n"+"Passenger 4 Name";
  }
  if(phone2<1000000000)
  {
   phone="\n"+"Phone Number";
  }    
  String j="Please Select"+name1+name2+name3+name4+phone+".";
  JOptionPane.showMessageDialog(this, j);
 }
 break;
 case 5:
 if(!nam1.equals(empty) && !nam2.equals(empty) && !nam3.equals(empty) && !nam4.equals(empty) 
    && !nam5.equals(empty) && phone2>=1000000000)
 {
  close();
  credit g=new credit();
  g.setVisible(true);
  credit.passno.setText(""+n);
  credit.total1.setText(""+total.getText());
 }
 else
 {
  if(nam1.equals(empty))
  {
   name1="\n"+"Passenger 1 Name";
  }
  if(nam2.equals(empty))
  {
   name2="\n"+"Passenger 2 Name";
  }
  if(nam3.equals(empty))
  {
   name3="\n"+"Passenger 3 Name";
  }
  if(nam4.equals(empty))
  {
   name4="\n"+"Passenger 4 Name";
  }
  if(nam5.equals(empty))
  {
   name5="\n"+"Passenger 5 Name";
  }
  if(phone2<1000000000)
  {
   phone="\n"+"Phone Number";
  }    
  String j="Please Enter"+name1+name2+name3+name4+name5+phone+".";
  JOptionPane.showMessageDialog(this, j);
 }
 break;
 default:
 break;    
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void s1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_s1ItemStateChanged
passenger();
t1.setText("");
t2.setText("");
t3.setText("");
t4.setText("");
t5.setText("");
int n=s1.getSelectedIndex() +1;
int cost=Integer.parseInt(price.getText());
total.setText(""+n*cost);
if(n==1)
{
 book.p1.setEnabled(true);
 book.t1.setEnabled(true);
}
if(n==2)
{
 book.p1.setEnabled(true);
 book.t1.setEnabled(true);
 book.p2.setEnabled(true);
 book.t2.setEnabled(true);
}
if(n==3)
{
 book.p1.setEnabled(true);
 book.t1.setEnabled(true);
 book.p2.setEnabled(true);
 book.t2.setEnabled(true);
 book.p3.setEnabled(true);
 book.t3.setEnabled(true);
}
if(n==4)
{
 book.p1.setEnabled(true);
 book.t1.setEnabled(true);
 book.p2.setEnabled(true);
 book.t2.setEnabled(true);
 book.p3.setEnabled(true);
 book.t3.setEnabled(true);
 book.p4.setEnabled(true);
 book.t4.setEnabled(true);
}
if(n==5)
{
 book.p1.setEnabled(true);
 book.t1.setEnabled(true);
 book.p2.setEnabled(true);
 book.t2.setEnabled(true);
 book.p3.setEnabled(true);
 book.t3.setEnabled(true);
 book.p4.setEnabled(true);
 book.t4.setEnabled(true);
 book.p5.setEnabled(true);
 book.t5.setEnabled(true);
}       // TODO add your handling code here:
    }//GEN-LAST:event_s1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
close();
Flight t=new Flight();
t.setVisible(true);
String u=user.getText();
Flight.user.setText(u);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel detail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel p1;
    public static javax.swing.JLabel p2;
    public static javax.swing.JLabel p3;
    public static javax.swing.JLabel p4;
    public static javax.swing.JLabel p5;
    public static javax.swing.JFormattedTextField phon;
    public static javax.swing.JTextField price;
    public static javax.swing.JComboBox<String> s1;
    public static javax.swing.JTextField t1;
    public static javax.swing.JTextField t2;
    public static javax.swing.JTextField t3;
    public static javax.swing.JTextField t4;
    public static javax.swing.JTextField t5;
    public static javax.swing.JTextField total;
    public static javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
