import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAJVEER
 */
public class credit extends javax.swing.JFrame {

    /**
     * Creates new form credit
     */
    public credit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ref = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        f2 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        f1 = new javax.swing.JFormattedTextField();
        l1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        trans = new javax.swing.JTextField();
        passno = new javax.swing.JTextField();
        total1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(570, 354));
        setPreferredSize(new java.awt.Dimension(570, 320));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(410, 240, 100, 30);

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(13, 240, 70, 30);

        t4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        t4.setToolTipText("Ex : 1234");
        getContentPane().add(t4);
        t4.setBounds(403, 196, 107, 30);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(79, 207, 22, 20);

        ref.setBackground(new java.awt.Color(255, 255, 255));
        ref.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ref.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(ref);
        ref.setBounds(10, 199, 65, 28);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Price Per Ticket");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 156, 141, 23);

        try {
            f2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(f2);
        f2.setBounds(403, 106, 107, 30);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Enter CVV");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 107, 151, 24);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Enter your 16- digit card number ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 64, 262, 25);

        try {
            f1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(f1);
        f1.setBounds(296, 66, 214, 30);

        l1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 0, 153));
        l1.setText("Enter Name On Card");
        getContentPane().add(l1);
        l1.setBounds(10, 20, 251, 25);

        t1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(296, 16, 214, 30);
        getContentPane().add(name1);
        name1.setBounds(410, 294, 6, 0);
        getContentPane().add(t2);
        t2.setBounds(214, 294, 6, 0);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Rs");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(377, 157, 22, 24);

        trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transActionPerformed(evt);
            }
        });
        getContentPane().add(trans);
        trans.setBounds(37, 256, 6, 0);
        getContentPane().add(passno);
        passno.setBounds(25, 256, 6, 0);

        total1.setEditable(false);
        total1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(total1);
        total1.setBounds(403, 151, 107, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air5.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 570, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void close()
{
    WindowEvent winClose=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClose);
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
double a=Math.random();
int a1=(int) (10*a);
double b=Math.random();
int b1=(int) (10*b);
double c=Math.random();
int c1=(int) (10*c);
double d=Math.random();
int d1=(int) (10*d);
int e=((a1*10 + b1)*10 + c1)*10 + d1;
ref.setText(""+e);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int random=Integer.parseInt(ref.getText());
int check=Integer.parseInt(t4.getText());
String nam=t1.getText();
String cv=f2.getText();
String f=f1.getText();
int lcv=cv.length();
String n="";
int l=f.length();
l--;
for(int x=0; x<=3; x++)
{
 char a=f.charAt(x);
 n=n+a;
}
for(int x=5; x<=8; x++)
{
 char a=f.charAt(x);
 n=n+a;
}
for(int x=10; x<=13; x++)
{
 char a=f.charAt(x);
 n=n+a;
}
for(int x=15; x<=18; x++)
{
 char a=f.charAt(x);
 n=n+a;
}
int ln=n.length();
int h=0;
for(int x=0; x<=ln-1;x++)
{
 char c=n.charAt(x);
 if(" ".equals(c+""))
 {
  h=h+1;
 }
}
t2.setText(""+n);
if(random==check && !nam.equals("") && lcv==3 && !cv.equals("") && !n.equals("") && h==0)
{    
 String b=t2.getText();
 int l2=b.length();
 if(1<=l2 && l2<16)
 {
  int l3=16-l2;
  for(int l4=0; l4<l3; l4++)
  {
   b="0"+b;
   t2.setText(b);
  }
 }
 if(l2==16)
 {
  t2.setText(b);
 }
 close();
 confirm con=new confirm();
 con.setVisible(true);
 int k=0;
 try
 {
  Class.forName("java.sql.Driver");
  Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","");
  Statement stmt=conn.createStatement();
  String query="select txn from transaction;";
  ResultSet rs=stmt.executeQuery(query);
  while(rs.next())
  {
   k=rs.getInt("txn")+1;
  }
  trans.setText(""+k);
  rs.close();
  stmt.close();
  conn.close();
 }
 catch(Exception e)
 {
  System.out.println(e);
 }
 String nam1=book.t1.getText();
 String nam2=book.t2.getText();
 String nam3=book.t3.getText();
 String nam4=book.t4.getText();
 String nam5=book.t5.getText();
 String phone=book.phon.getText();
 String strt=(String) Flight.f1.getSelectedItem();
 String stp=(String) Flight.f2.getSelectedItem();
 SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
 String date2 = formatter.format(Flight.d1.getDate());
 String n1=passno.getText();
 Calendar cal = Calendar.getInstance();
 Date t=cal.getTime();
 String date1=formatter.format(t);
 String bookno=trans.getText();
 String sn=book.user.getText();
 String pric=book.price.getText();
 String total=total1.getText();
 try
 {
  Class.forName("java.sql.Driver");
  Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","");
  Statement stmt=conn.createStatement();
  String query="insert into transaction values ("+bookno+","+n1+",'"+nam1+"','"+nam2+"','"
          +nam3+"','"+nam4+"','"+nam5+"','"+strt+"','"+stp+"','"+date1+"','"+date2+"',"+sn
          +",'"+phone+"',"+pric+","+total+",'"+n+"','"+nam+"');";
  stmt.execute(query);
  stmt.close();
  conn.close();
 } 
 catch (Exception e) 
 {
  System.out.print(e);
 }  
}

else
{
 String s="Please Check";
 if(random!=check)
 {
  s=s+"\n" +"Security Code";            
 }
 if(h!=0 || n.equals(""))
 {
  s=s+"\n" +"Card Number Entered";            
 }
 if(lcv!=3 || cv.equals(""))
 {
  s=s+"\n" +"CVV Number";            
 }
 if(nam.equals(""))
 {
  s=s+"\n" +"Name On Card";           
 }
 JOptionPane.showMessageDialog(this,s);
 double a=Math.random();
 int a1=(int) (10*a);
 double b=Math.random();
 int b1=(int) (10*b);
 double c=Math.random();
 int c1=(int) (10*c);
 double d=Math.random();
 int d1=(int) (10*d);
 int e=((a1*10 + b1)*10 + c1)*10 + d1;
 ref.setText(""+e);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
close();
Flight r=new Flight();
r.setVisible(true);
String a=book.user.getText();
Flight.user.setText(a);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
double a=Math.random();  
int a1=(int) (10*a);
double b=Math.random();  
int b1=(int) (10*b);
double c=Math.random();  
int c1=(int) (10*c);
double d=Math.random();  
int d1=(int) (10*d);
int e=((a1*10 + b1)*10 + c1)*10 + d1;
ref.setText(""+e);     
Font font=t4.getFont();
f1.setFont(font);
f2.setFont(font);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new credit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JFormattedTextField f1;
    public static javax.swing.JFormattedTextField f2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel l1;
    public static javax.swing.JTextField name1;
    public static javax.swing.JTextField passno;
    private javax.swing.JLabel ref;
    public static javax.swing.JTextField t1;
    public static javax.swing.JTextField t2;
    public static javax.swing.JTextField t4;
    public static javax.swing.JTextField total1;
    public static javax.swing.JTextField trans;
    // End of variables declaration//GEN-END:variables

    
}
