

import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAJVEER
 */
public class Flight extends javax.swing.JFrame {

    /**
     * Creates new form lis1
     */
    public Flight() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        s1 = new javax.swing.JComboBox();
        f1 = new javax.swing.JComboBox<>();
        f2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        user = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        d1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(743, 417));
        setPreferredSize(new java.awt.Dimension(747, 445));
        setResizable(false);
        setSize(new java.awt.Dimension(743, 417));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Choose Flight");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 246, 152, 34);

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 51));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 50, 90, 40);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Enter No. Seats");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(13, 367, 127, 31);

        s1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        s1.setForeground(new java.awt.Color(0, 0, 153));
        s1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(s1);
        s1.setBounds(150, 370, 64, 31);

        f1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        f1.setForeground(new java.awt.Color(0, 0, 153));
        f1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Origin" }));
        f1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                f1ItemStateChanged(evt);
            }
        });
        getContentPane().add(f1);
        f1.setBounds(10, 286, 185, 32);

        f2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        f2.setForeground(new java.awt.Color(0, 0, 153));
        f2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Destinaton" }));
        getContentPane().add(f2);
        f2.setBounds(237, 286, 176, 32);

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(436, 367, 73, 31);

        user.setEditable(false);
        user.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        user.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(user);
        user.setBounds(500, 290, 89, 32);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("User ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(436, 286, 73, 32);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Travel Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(253, 325, 138, 36);

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Transactions");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 290, 140, 38);

        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 360, 117, 32);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IndiGo_Logo.jpg"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(1000, 1000));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 10, 60, 59);
        getContentPane().add(d1);
        d1.setBounds(240, 370, 160, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air2.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1, -4, 743, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void close()
{
    WindowEvent winClose=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClose);
}
double Total=0;
int x;
double amount;
double amount1;
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
Calendar cal = Calendar.getInstance();
Date t=cal.getTime();
d1.setMinSelectableDate(t);
d1.setDate(t);
System.out.print(t);
Font f=user.getFont();
d1.setFont(f);
try
{
 Class.forName("java.sql.Driver");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","");
 Statement stmt=con.createStatement();
 String query="select * from cities;";
 ResultSet rs=stmt.executeQuery(query);
 while(rs.next())
 {
  String city=rs.getString("origin");
  f1.addItem(city);
 }
 rs.close();
 stmt.close();
 con.close();
} 
catch (Exception e) 
{
 System.out.print(e);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void f1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_f1ItemStateChanged
int x=f1.getSelectedIndex();
if(x==0)
{   
 f2.removeAllItems();
 f2.addItem("Select Destination");
 System.out.println("hello");
}
else
{ 
 String origin=(String) f1.getSelectedItem();
 f2.removeAllItems();
 f2.addItem("Select Destination");
 try
 {
  Class.forName("java.sql.Driver");
  Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","");
  Statement stmt=con.createStatement();
  String query="select * from "+origin+";";
  ResultSet rs=stmt.executeQuery(query);
  while(rs.next())
  {
   String stp=rs.getString("stop");
   f2.addItem(stp);
  }
  rs.close();
  stmt.close();
  con.close();
 } 
 catch (Exception e) 
 {
  System.out.print(e);
 }   
}        // TODO add your handling code here:
    }//GEN-LAST:event_f1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String start="";
String stop="";
String date2="";
int n=s1.getSelectedIndex() +1;
int n1=s1.getSelectedIndex();
SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
String date1 = formatter.format(d1.getDate());
int o1=f1.getSelectedIndex();
int d1=f2.getSelectedIndex();
if(o1!=0 && d1!=0 && !date1.equals(""))
{
 close();
 book c=new book();
 c.setVisible(true);
 book.user.setText(""+user.getText());
 book.detail.setText(f1.getSelectedItem()+" - "+f2.getSelectedItem());
 book.p1.setEnabled(false);
 book.t1.setEnabled(false);
 book.p2.setEnabled(false);
 book.t2.setEnabled(false);
 book.p3.setEnabled(false);
 book.t3.setEnabled(false);
 book.p4.setEnabled(false);
 book.t4.setEnabled(false);
 book.p5.setEnabled(false);
 book.t5.setEnabled(false);
 String origin=(String) f1.getSelectedItem();
 int cost = 0;
 try
 {
  Class.forName("java.sql.Driver");
  Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","");
  Statement stmt=con.createStatement();
  String query="select price from "+origin+" where stop like '"+f2.getSelectedItem()+"';";
  ResultSet rs=stmt.executeQuery(query);
  while(rs.next())
  {
   cost=rs.getInt("price");
  }
  rs.close();
  stmt.close();
  con.close();
 } 
 catch (Exception e) 
 {
  System.out.print(e);
 }
 book.price.setText(""+cost);
 book.total.setText(""+n*cost);
 if(n==1)
 {
  book.p1.setEnabled(true);
  book.t1.setEnabled(true);
 }
 if(n==2)
 {
  book.p1.setEnabled(true);
  book.t1.setEnabled(true);
  book.p2.setEnabled(true);
  book.t2.setEnabled(true);
 } 
 if(n==3)
 {
  book.p1.setEnabled(true);
  book.t1.setEnabled(true);
  book.p2.setEnabled(true);
  book.t2.setEnabled(true);
  book.p3.setEnabled(true);
  book.t3.setEnabled(true);
 } 
 if(n==4)
 {
  book.p1.setEnabled(true);
  book.t1.setEnabled(true);
  book.p2.setEnabled(true);
  book.t2.setEnabled(true);
  book.p3.setEnabled(true);
  book.t3.setEnabled(true);
  book.p4.setEnabled(true);
  book.t4.setEnabled(true);
 } 
 if(n==5)
 {
  book.p1.setEnabled(true);
  book.t1.setEnabled(true);
  book.p2.setEnabled(true);
  book.t2.setEnabled(true);
  book.p3.setEnabled(true);
  book.t3.setEnabled(true);
  book.p4.setEnabled(true);
  book.t4.setEnabled(true);
  book.p5.setEnabled(true);
  book.t5.setEnabled(true);
 }
 book.s1.setSelectedIndex(n1);
}

else
{
 if(o1==0)
 {
  start="\n"+"Origin";
 }    
 if(d1==0)
 {
  stop="\n"+"Destination";
 }    
 if(date1.equals(""))
 {
  date2="\n"+"Date Of Travelling";
 }    
 String j="Please Select"+start+stop+date2+".";
 JOptionPane.showMessageDialog(this, j);
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
close();
transaction b=new transaction();
b.setVisible(true);
String id=user.getText();
transaction.user.setText(id);
try
{
 Class.forName("java.sql.Driver");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","");
 Statement stmt=con.createStatement();
 String query="select sno,txn from transaction where sno like '"+id+"';";
 ResultSet rs=stmt.executeQuery(query);
 while(rs.next())
 {
  String t=rs.getString("txn");
  transaction.txn.addItem(t);                         
 }
 rs.close();
 stmt.close();
 con.close();
} 
catch(Exception e)
{
 System.out.println(e);
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
close();
login a=new login();
a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JDateChooser d1;
    public static javax.swing.JComboBox<String> f1;
    public static javax.swing.JComboBox<String> f2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox s1;
    public static javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
