
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAJVEER
 */
public class transaction extends javax.swing.JFrame {

    /**
     * Creates new form transaction
     */
    public transaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txn = new javax.swing.JComboBox<>();
        from = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(426, 463));
        setPreferredSize(new java.awt.Dimension(420, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        txn.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txn.setForeground(new java.awt.Color(0, 0, 153));
        txn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Transaction" }));
        txn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txnItemStateChanged(evt);
            }
        });
        getContentPane().add(txn);
        txn.setBounds(10, 101, 190, 40);

        from.setEditable(false);
        from.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(from);
        from.setBounds(6, 218, 130, 40);

        to.setEditable(false);
        to.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(to);
        to.setBounds(142, 218, 130, 40);

        pass.setEditable(false);
        pass.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(pass);
        pass.setBounds(282, 218, 130, 40);

        price.setEditable(false);
        price.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(price);
        price.setBounds(10, 314, 126, 40);

        total.setEditable(false);
        total.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(total);
        total.setBounds(142, 314, 130, 40);

        date.setEditable(false);
        date.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(date);
        date.setBounds(282, 314, 130, 40);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("From");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 176, 52, 30);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("To");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(142, 176, 22, 30);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Number Of Seats");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 180, 138, 24);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 275, 58, 24);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Total");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(142, 275, 41, 24);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Travel Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(282, 275, 94, 24);

        user.setEditable(false);
        user.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(user);
        user.setBounds(282, 102, 128, 40);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText(" User ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(278, 60, 130, 40);

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 361, 118, 40);

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(294, 361, 118, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IndiGo_Logo.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 10, 60, 59);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air6.jpg"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(1000, 1000));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 420, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void close()
{
    WindowEvent winClose=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClose);
}
    private void txnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txnItemStateChanged
String tx=(String) txn.getSelectedItem();
try
{
 Class.forName("java.sql.Driver");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","");
 Statement stmt=con.createStatement();
 String query="select pass_no,start,stop,traveld,price,total from transaction where txn like '"+tx+"';";
 ResultSet rs=stmt.executeQuery(query);
 while(rs.next())
 {   
  String passno=rs.getString("pass_no");
  String strt=rs.getString("start");
  String stp=rs.getString("stop");
  String dat=rs.getString("traveld");
  String pric=rs.getString("price");
  String net=rs.getString("total");
  from.setText(strt);
  to.setText(stp);
  pass.setText(passno);
  price.setText(pric);
  total.setText(net);
  date.setText(dat);  
 }
 rs.close();
 stmt.close();
 con.close();
} 
catch(Exception e)
{
  System.out.println(e);
}        // TODO add your handling code here:
    }//GEN-LAST:event_txnItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
close();
Flight f=new Flight();
f.setVisible(true);
String id=user.getText();
Flight.user.setText(id);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
close();
login a=new login();
a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JTextField from;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField price;
    private javax.swing.JTextField to;
    private javax.swing.JTextField total;
    public static javax.swing.JComboBox<String> txn;
    public static javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
